import os
from dotenv import load_dotenv
# Load variables from .env file
load_dotenv()

LOG_FILE_NAME = os.environ["LOG_FILE_NAME"]
DEFAULT_URL = os.environ["DEFAULT_URL"]
DEFAULT_WORDLIST = os.environ["DEFAULT_WORDLIST"]
DEFAULT_SQL_WORDLIST = os.environ["DEFAULT_SQL_WORDLIST"]
DEFAULT_XSS_WORDLIST = os.environ["DEFAULT_XSS_WORDLIST"]
DEFAULT_XML_WORDLIST = os.environ["DEFAULT_XML_WORDLIST"]
DEFAULT_HTTP_VERBS_WORDLIST = os.environ["DEFAULT_HTTP_VERBS_WORDLIST"]
DEFAULT_RECURSION_WORDLIST = os.environ["DEFAULT_RECURSION_WORDLIST"]
DEFAULT_RANGE = os.environ["DEFAULT_RANGE"]
DEFAULT_POST_DATA = os.environ["DEFAULT_POST_DATA"]
DEFAULT_RECURSION_DEPTH = os.environ["DEFAULT_RECURSION_DEPTH"]
